const COMP = '/fan-kit/Components';

export const STANDARD_COMPONENT_ICONS: Record<string, string> = {
  'Elven Wood':          `${COMP}/elvenwood.png`,
  'Iron Pine Cone':      `${COMP}/redpinecone.png`,
  'Glow Shroom':         `${COMP}/glowingmushrooms.png`,
  'Silver Dust':         `${COMP}/arcanedust.png`,
  'Webbed Wing':         `${COMP}/webbedwings.png`,
  'Precious Gem':        `${COMP}/preciousgem.png`,
  'Living Root':         `${COMP}/livingroots.png`,
  'Rustwyrm Scale':      `${COMP}/darkscale.png`,
  'Deep Pearl':          `${COMP}/icypearl.png`,
  'White Sand':          `${COMP}/whitesand.png`,
  'Bronze Fang':         `${COMP}/sharpfang.png`,
  'Moon Crystal':        `${COMP}/mooncrystal.png`,
  'Evil Eye':            `${COMP}/evileye.png`,
  'Silk Scarab':         `${COMP}/silkscarab.png`,
  'Star Metal':          `${COMP}/starmetal.png`,
  'Ancient Marble':      `${COMP}/ancientmarble.png`,
  'Overgrown Vine':      `${COMP}/overgrownvine.png`,
  'Chronos Crystal':     `${COMP}/timecrystal.png`,
  'Spooky Ectoplasm':    `${COMP}/ectoplasm.png`,
  'Thread of Fate':      `${COMP}/sewingthread.png`,
  'Ghastly Pennant':     `${COMP}/ghostflag.png`,
  'Deep Coral':          `${COMP}/deepcoral.png`,
  'Crystal Lullaby':     `${COMP}/sirenshard.png`,
  'Precious Shell':      `${COMP}/goldshell.png`,
  'Grim Talon':          `${COMP}/grimtalon.png`,
  'Zirconia Eggshell':   `${COMP}/crystalegg.png`,
  'Boreal Gale':         `${COMP}/icybreeze.png`,
  'Crush Claw':          `${COMP}/crabclaw.png`,
  'Raw Obsidian':        `${COMP}/obsidian.png`,
  'Magma Core':          `${COMP}/magmacore.png`,
  "Outsider's Claw":     `${COMP}/voidcrystal.png`,
  'All-Seeing Eye':      `${COMP}/voideye.png`,
  'Astral Fabric':       `${COMP}/voidcloth.png`,
  'Demigod Pinion':      `${COMP}/demigodpinion.png`,
  "Heaven's Crest":      `${COMP}/heavencrest.png`,
  'Divine Spark':        `${COMP}/divinespark.png`,
  'Mysterious Fossil':   `${COMP}/oldfossil.png`,
  'Dinosaur Leather':    `${COMP}/dinoleather.png`,
  'Ancient Amber':       `${COMP}/amber.png`,
  'Elder Wood':          `${COMP}/tw_elvenwood.png`,
  'Man-goroots':         `${COMP}/tw_livingroots.png`,
  'Full Moon Crystal':   `${COMP}/tw_mooncrystal.png`,
  'Star Metal Ingot':    `${COMP}/tw_starmetal.png`,
  'Kingtoplasm':         `${COMP}/tw_ectoplasm.png`,
  'Marble Pillar':       `${COMP}/tw_ancientmarble.png`,
  'Xzyur Claw':          `${COMP}/alienclaw.png`,
  'Xzyur Eye':           `${COMP}/alieneye.png`,
  'Alien Bulb':          `${COMP}/alienmushroom.png`,
  'Wing Nexus':          `${COMP}/tw_webbedwings.png`,
  'Paramount Gem':       `${COMP}/tw_preciousgem.png`,
  'Hybridized Vine':     `${COMP}/tw_overgrownvine.png`,
  'Rusted Pickaxe':      `${COMP}/rustyaxe.png`,
  'Deterioriated Book':  `${COMP}/rustyscroll.png`,
  'Faded Cowl':          `${COMP}/rustyroguehat.png`,
  'Tattered Binder':     `${COMP}/rustycardscroll.png`,
  'Broken Torc':         `${COMP}/rustyamulet.png`,
  'Rusted Katana':       `${COMP}/rustysword.png`,
  'Rusted Tassets':      `${COMP}/rustyheavyarmor.png`,
  'Chunk of Boots':      `${COMP}/rustyboots.png`,
  'Ruined Mace':         `${COMP}/rustymace.png`,
  'Rusted Cannon':       `${COMP}/rustygun.png`,
  'Spent Knowledge':     `${COMP}/rustycup.png`,
  'Golden Chunk':        `${COMP}/tabletfragment.png`,
  'Opulent Jewel':       `${COMP}/tabletjewel.png`,
  'Platinum Bangles':    `${COMP}/platinumjewel.png`,
  'Precious Pearl':      `${COMP}/coraljewel.png`,
  'Sigil of Grace':      `${COMP}/gracesigil.png`,
  'Sigil of Spark':      `${COMP}/sparksigil.png`,
  'Sigil of Might':      `${COMP}/mightsigil.png`,
  'Sigil of True Grace': `${COMP}/gracesigil2.png`,
  'Sigil of True Spark': `${COMP}/sparksigil2.png`,
  'Sigil of True Might': `${COMP}/mightsigil2.png`,
};
